AWSTemplateFormatVersion: 2010-09-09
Description: Hello Template
#Metadata: 

#Parameters: 

#Mappings: 

#Conditions: 

Resources: 
  mybucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: 'aws.amazon.com'
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - 'mybucket'
      - WebsiteURL
    Description: 'Website URL'